# @format
# fhcebihi/vote
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db-app-pod
spec:
  containers:
    - name: db
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
